spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: gulimall-third-party
server:
  port: 30000

alibaba:
  cloud:
    access-key: LTAI5tJcwnhokAPdHR1VLdka
    secret-key: UkET5z4z6uDI8cWklaamjNhF9FnSiv
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      bucket: gulimall-yalong
